import type { Metadata } from "next";
import type { BookReview, Event, Seo, SiteSettings } from "@/lib/content/types";

/** Share image generated by `app/opengraph-image.tsx`. */
const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Junto Community Alliance. Learn Something. Meet Someone. At the Library.",
};

/**
 * Page metadata with complete Open Graph and Twitter tags. Next.js replaces
 * (not merges) these objects per page, so every field is set here.
 */
export function pageMetadata(seo: Seo, path: string, site: SiteSettings): Metadata {
  return {
    title: { absolute: seo.title },
    description: seo.description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: site.name,
      locale: "en_US",
      title: seo.title,
      description: seo.description,
      url: path,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: seo.title,
      description: seo.description,
      images: [OG_IMAGE.url],
    },
  };
}

/** schema.org `Organization` and `WebSite` data, so search results can show the site name and logo. */
export function organizationJsonLd(site: SiteSettings) {
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "NonprofitOrganization",
        "@id": `${site.url}/#organization`,
        name: site.name,
        alternateName: site.shortName,
        url: site.url,
        logo: `${site.url}${site.logos.stacked.src}`,
        email: site.contactEmail,
        slogan: site.tagline,
        address: { "@type": "PostalAddress", addressLocality: "Phoenix", addressRegion: "AZ", addressCountry: "US" },
      },
      {
        "@type": "WebSite",
        "@id": `${site.url}/#website`,
        name: site.name,
        alternateName: site.shortName,
        url: site.url,
        publisher: { "@id": `${site.url}/#organization` },
      },
    ],
  };
}

/** schema.org `Review` of a `Book`. Only meaningful once the review has text. */
export function reviewJsonLd(review: BookReview, site: SiteSettings) {
  return {
    "@context": "https://schema.org",
    "@type": "Review",
    url: `${site.url}${review.path}`,
    itemReviewed: {
      "@type": "Book",
      name: review.book.title,
      author: { "@type": "Person", name: review.book.author },
    },
    author: { "@type": "Person", name: review.reviewer.name },
    publisher: { "@type": "Organization", name: site.name },
    ...(review.rating !== null && {
      reviewRating: { "@type": "Rating", ratingValue: review.rating, bestRating: 5 },
    }),
    reviewBody: review.body?.join("\n\n"),
  };
}

/** schema.org `Event` structured data for search engines. */
export function eventJsonLd(event: Event, site: SiteSettings) {
  const { inPerson, online } = event.attendance;
  const mode =
    inPerson && online ? "MixedEventAttendanceMode" : online ? "OnlineEventAttendanceMode" : "OfflineEventAttendanceMode";

  const locations = [
    inPerson && {
      "@type": "Place",
      name: inPerson.venue.name,
      address: {
        "@type": "PostalAddress",
        streetAddress: inPerson.venue.streetAddress,
        addressLocality: inPerson.venue.locality,
        addressRegion: inPerson.venue.region,
        postalCode: inPerson.venue.postalCode,
        addressCountry: inPerson.venue.country,
      },
    },
    online && { "@type": "VirtualLocation", url: event.registration.url },
  ].filter(Boolean);

  return {
    "@context": "https://schema.org",
    "@type": "Event",
    name: event.name,
    description: event.seo.description,
    startDate: event.startsAt,
    endDate: event.endsAt,
    eventStatus: "https://schema.org/EventScheduled",
    eventAttendanceMode: `https://schema.org/${mode}`,
    location: locations.length === 1 ? locations[0] : locations,
    image: [`${site.url}${site.logos.stacked.src}`],
    url: `${site.url}${event.path}`,
    offers: {
      "@type": "Offer",
      price: event.price,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      url: event.registration.url,
    },
    organizer: { "@type": "Organization", name: site.name, url: site.url },
    performer: { "@type": "Person", name: event.presenter.name },
  };
}

/** Serializes JSON-LD safely for a `<script>` tag. */
export function jsonLdScript(data: unknown) {
  return JSON.stringify(data).replace(/</g, "\\u003c");
}
